appbundle_index_index:
    path: /
    defaults: { _controller: AppBundle:Home:index }

appbundle_home_index:
    path: /h
    defaults: { _controller: AppBundle:Home:home }

appbundle_home_search:
    path: /h/search
    defaults: { _controller: AppBundle:Home:search }

adminbundle_index_index:
    path: /admin
    defaults: { _controller: AdminBundle:Index:index }

adminbundle_api_test:
    path: /admin/api/test/{_requestName}
    defaults: { _controller: AdminBundle:API:test, _requestName: "" }

adminbundle_recache_gods:
    path: /admin/recache/gods
    defaults: { _controller: AdminBundle:God:recache }

adminbundle_recache_items:
    path: /admin/recache/items
    defaults: { _controller: AdminBundle:Item:recache }

godbundle_god_index:
    path: /g
    defaults: { _controller: GodBundle:God:index}

godbundle_god_god:
    path: /g/{_id}
    defaults: { _controller: GodBundle:God:god, _id: "-1" }

godbundle_tierlist_index:
    path: /t
    defaults: { _controller: GodBundle:Tierlist:index}

godbundle_tierlist_new:
    path: /t/new
    defaults: { _controller: GodBundle:Tierlist:new}

godbundle_tierlist_save:
    path: /t/save
    defaults: { _controller: GodBundle:Tierlist:save}

godbundle_tierlist_list:
    path: /t/{_unique}
    defaults: { _controller: GodBundle:Tierlist:list, _unique: "-1"}

fos_user_security:
    resource: "@UserBundle/Resources/config/routing/security.xml"
    prefix: /user/login

fos_user_profile:
    resource: "@UserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

fos_user_register:
    resource: "@UserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_security_logout:
    pattern:  /user/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user/profile