# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    appbundle.util.searchhelper:
        class: AppBundle\Util\SearchHelper
        arguments:
            serviceContainer: "@service_container"
            router: "@router"
            entityManager: "@doctrine.orm.entity_manager"
    appbundle.util.apihelper:
        class: AppBundle\Util\ApiHelper
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
    appbundle.util.awshelper:
        class: AppBundle\Util\AwsHelper
        arguments:
            serviceContainer: "@service_container"
    godbundle.util.tierlisthelper:
        class: GodBundle\Util\TierlistHelper
        arguments:
            serviceContainer: "@service_container"
    matchbundle.command.update:
        class: MatchBundle\Console\Command\UpdateMatchCommand
        tags:
            - { name: match.update }
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            - %database_user%
            - %database_password%