# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    api.gamedataprovider:
        class: AdminBundle\Util\GameDataProvider
        arguments:
            serviceContainer: "@service_container"
    amazon.s3:
        class: AdminBundle\Util\Amazon\S3
        arguments:
            serviceContainer: "@service_container"
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            - %database_user%
            - %database_password%